### ISSUE TITLE
Ciera-generated code produces ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by johnrwolfe** [johnrwolfe/CarPark#32]
As it turns out, https://support.onefact.net/issues/11933, indicates that attributes of array type produce Java compilation errors.  It's not clear why the Carpark usage compiles and then produces a runtime error, but at this point Ciera does not support arrays as attributes.
For now, this is of no consequence for the Carpark application, as the array in question is not being used, and will become unnecessary when the Panda-updated version of the TIM EE is available.  Leaving this issue open until then.

Stack trace is below.  
----
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at interactivetesting.carparkcontrol.datetime.impl.TimeUtilImpl$CLASS.Init(TimeUtilImpl.java:277)
	at interactivetesting.carparkcontrol.CarparkControlTestSupport.InitializeEpoch(CarparkControlTestSupport.java:28)
	at interactivetesting.carparkcontrol.CarparkControlTestSupport.deliver(CarparkControlTestSupport.java:44)
	at io.ciera.runtime.summit.interfaces.Port$1.run(Port.java:23)
	at io.ciera.runtime.summit.application.ApplicationExecutor.performTransaction(ApplicationExecutor.java:121)
	at io.ciera.runtime.summit.application.ApplicationExecutor.run(ApplicationExecutor.java:92)
	at interactivetesting.InteractiveTestingApplication.start(InteractiveTestingApplication.java:81)
	at interactivetesting.InteractiveTestingApplication.main(InteractiveTestingApplication.java:114)

**Comment by johnrwolfe** [comment]
Panda has been delivered, so the Carpark model has no immediate need for arrays.
